// One-time interactive setup. Run with: npm run setup
//
// Asks for the two secrets only you can provide (the Telegram bot token
// and the admin passcode you want to use), then writes a ready-to-use
// .env file. Everything else (hashing the passcode, formatting the file)
// happens automatically.

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const bcrypt = require('bcryptjs');

const ENV_PATH = path.join(__dirname, '..', '.env');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((resolve) => rl.question(q, resolve));

async function main() {
  console.log('\n=== Booking site setup ===\n');

  if (fs.existsSync(ENV_PATH)) {
    const overwrite = await ask('.env already exists. Overwrite it? (y/N): ');
    if (!/^y(es)?$/i.test(overwrite.trim())) {
      console.log('Left the existing .env untouched.\n');
      rl.close();
      return;
    }
  }

  console.log('Get this from @BotFather on Telegram (send /newbot if you haven\'t made one yet).');
  const token = (await ask('Paste your Telegram Bot Token: ')).trim();

  console.log('\nThis is the password you\'ll use to log into the hidden admin dashboard at /admin/dashboard.html');
  const passcode = (await ask('Choose an admin passcode: ')).trim();

  rl.close();

  if (!token) {
    console.error('\nNo bot token entered — aborting. Run "npm run setup" again when you have one.');
    process.exit(1);
  }
  if (!passcode) {
    console.error('\nNo passcode entered — aborting. Run "npm run setup" again.');
    process.exit(1);
  }

  const hash = bcrypt.hashSync(passcode, 12);

  const envContents = `# Generated by "npm run setup" on ${new Date().toISOString()}
TELEGRAM_BOT_TOKEN=${token}
ADMIN_PASSWORD_HASH=${hash}
NODE_ENV=development
PORT=3000
`;

  fs.writeFileSync(ENV_PATH, envContents);
  console.log('\n.env written. You can now run: npm start\n');
}

main();
